version: '3.8'

services:
  mongodb:
    build: ./mongo
    container_name: movie-api-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  mongodb_seed:
    build: ./mongo
    container_name: movie-api-db-seed
    command: ["bash", "/docker-entrypoint-initdb.d/init-mongo.sh"]
    depends_on:
      - mongodb


volumes:
  mongo-data:
    driver: local